# This is a basic workflow to help you get started with Actions

name: Helm Chart Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths: [ 'charts/**' ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Helm tool installer
        uses: Azure/setup-helm@v4
        with:
          version: latest

      - name: Helm packaging and reposotiry indexing
        run: ./.github/scripts/helm_packaging_and_repo_indexing.sh     

      - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
        # Only run on main branch push (e.g. after pull request merge).
        #if: github.event_name == 'push'
        run: |
          cd ${GITHUB_WORKSPACE}
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -a -m "Helm packages publication is up-to-date."
          git push

